### ISSUE TITLE
How to loop through edgar.get_company_facts(cik="320193")

### ISSUE THREAD

**Issue by TimdBui** [jadchaar/sec-edgar-api#1]
Hello, thank you for creating a wonderful library. It is very helpful for me and I am sure many benefit for your work. I am very new to Python and am trying to learn it. Is there anyway I can send CIK to "edgar.get_company_facts(cik="320193")" from a list of CIKs (Python For Loop)? Thank you!

**Comment by gnzsnz** [comment]
something like this should work

cik_list = ["320193", ....]
facts = [edgar.get_company_facts(cik=cik) for cik in cik_list]

**Comment by jadchaar** [comment]
Thanks @gnzsnz this is the preferred method for looping over and getting facts for CIKs in a loop.
