### ISSUE TITLE
pyrate-limiter dependency drift introduced breaking changes

### ISSUE THREAD

**Issue by 4umo** [jadchaar/sec-edgar-api#5]
this is the most recent version that works:
```
pyrate-limiter==2.10.0
```
here's the breaking major version bump 2 weeks ago: https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.0.0

**Comment by jadchaar** [comment]
Thanks for reporting. This is fixed by PR https://github.com/jadchaar/sec-edgar-api/pull/6. I just realized v1.1 of this package to address this.
