### ISSUE TITLE
HOWTO - mute logging

### ISSUE THREAD

**Issue by gnzsnz** [jadchaar/sec-edgar-api#7]
I find a bit annoying the the logging messages from pyrate_limiter, so i tought that i migh share a simple recipe to mute it.

```python
from sec_edgar_api import EdgarClient

import logging
logging.getLogger("pyrate_limiter").setLevel(logging.WARNING)

edgar = EdgarClient(user_agent="<Sample Company Name> <Admin Contact>@<Sample Company Domain>")
edgar.get_submissions(cik="320193")
```

This allows to keep ´INFO´logging output clean of pyrate_limit

**Comment by jadchaar** [comment]
Thanks for raising this issue. Pyrate limiter has changed logging to debug mode in a newer package release, so I have bumped the dependency.
